### ISSUE TITLE
Aucun message d'erreur sur l'ajout de question

### ISSUE THREAD

**Issue by Azdracito** [tchapuis/osteo-training#2]
Pas de message d'erreur quand la question est vide
![Capture d'écran :](https://user-images.githubusercontent.com/50703309/95463561-2f0ce880-0979-11eb-9191-196c54ca7a4b.png)

**Comment by ghost** [comment]
Pareil quand la *réponse* est vide

**Comment by tchapuis** [comment]
Added required attributes on all inputs
