### ISSUE TITLE
Synchronisation du quiz et des questions

### ISSUE THREAD

**Issue by ghost** [tchapuis/osteo-training#4]
Description du test : 
-  j'ai lancé un quiz dans un onglet, et avancé de plusieurs questions
- dans un second onglet, j'ai ajouté une question
- retour sur le 1er : en avançant dans le quiz, j'ai vu apparaître ma nouvelle question, ainsi que les questions que j'avais déjà passé

Ça me suggère que le quiz a été remis à zéro lors de l'ajout de la nouvelle question : est-ce que c'est le comportement prévu ?

**Comment by tchapuis** [comment]
Changed how the list of questions is copied to the quiz.
